# Generated by Django 5.0.4 on 2024-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_field1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_field2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
