# Generated by Django 5.0.4 on 2024-04-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_rename_event_myevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myevent',
            name='user',
        ),
    ]
