# Generated by Django 5.0.4 on 2024-04-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_myevent_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myevent',
            name='creator_id',
        ),
    ]
