# Generated by Django 5.0.4 on 2024-04-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_rename_creator_id_myevent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myevent',
            old_name='date',
            new_name='date1',
        ),
    ]
