# Generated by Django 5.0.4 on 2024-04-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_rename_date_myevent_date1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myevent',
            old_name='date1',
            new_name='date',
        ),
    ]
