# Generated by Django 5.0.4 on 2024-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pets_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name=()),
        ),
        migrations.AddField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/<int:user_id>/pets'),
        ),
    ]
