# Generated by Django 5.0.4 on 2024-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pets_app', '0002_remove_pet_birth_date_pet_age_pet_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/pets'),
        ),
    ]
