# Generated by Django 5.0.4 on 2024-04-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_pets_app', '0005_alter_pet_city_alter_pet_color_alter_pet_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='date_tatto',
            new_name='date_tattoo',
        ),
    ]
